### ISSUE TITLE
getPageNodes() must be of the type array, null returned

### ISSUE THREAD

**Issue by eiswurm** [m-vo/contao-facebook-import#14]
After upgrading from version 2 to 3 I get the following errors when I try to sync items manually:

Return value of Mvo\ContaoFacebookImport\GraphApi\GraphApiReader::getPageNodes() must be of the type array, null returned

**Comment by NinaG** [comment]
Same here

**Comment by m-vo** [comment]
Did you follow the [update instructions](https://github.com/m-vo/contao-facebook-import/blob/master/CHANGELOG.md#how-to-migrate-from-version-2)? 

Does the problem persist if you drop (or rename) and recreate the existing tables?

**Comment by eiswurm** [comment]
Same error, still after dropping the tables and recreating via Installtool

**Comment by m-vo** [comment]
I hardened the synchronizer logic in f8e4448c2ead2986729e6f280ac6f4b2f2110c5c so that the error shouldn't appear anymore. It however means something got wrong when trying to access the Facebook API anyways as `null` is only returned in the case of an error. 

@eiswurm @NinaG Please have a look into your system log and see if there is an error listed like `Facebook SDK: An error occurred querying edge of entity %s: %s [Code %s]`. If you've got the feeling this is a problem with this bundle feel free to open a new issue.
