### ISSUE TITLE
German umlauts not encoded correctly

### ISSUE THREAD

**Issue by maettyhawk** [m-vo/contao-facebook-import#2]
Just installed your plugin to check if it suits my requirements. I expected the plugin to somehow import FB events (current as well as past ones) as "real" event instances in Contao what it unfortunately didn't. While checking the imported events I saw that German umlauts were not encoded correctly (f.e. ü as Ã¼ and so on).

**Comment by m-vo** [comment]
I did not want the facebook events to be imported as contao events in my original scenario, so that is simply why it's implemented like this. It wouldn't be hard to add a feature to support an import as a native event as well. 

Thanks for reporting the encoding problem. This should only occur in the backend, right? (That is what I'm aware of but did not have any time to fix yet).

**Comment by maettyhawk** [comment]
Yes, stumbled upon the encoding errors in the backend.

**Comment by m-vo** [comment]
fixed in v2.0.0
